name: "Deploy website to hosts"

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  NODE_ENV: "production"

jobs:
  build-static:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm ci
      - run: npm run build:static
      - uses: actions/upload-artifact@v4
        with:
          name: static
          path: dist/
          if-no-files-found: error
          overwrite: true

  build-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm ci
      - run: npm run build:server
      - name: Build image
        run: |
          docker build -t alts-alt/website:prod \
            --build-arg WEBSITE_PORT=4321 \
            --build-arg SERVER_PORT=8000 \
            --build-arg SERVER_HOST=server \
            .
      - name: Export image
        run: docker save alts-alt/website:prod | gzip > website-image.tar.gz
      - uses: actions/upload-artifact@v4
        with:
          name: website-image
          path: website-image.tar.gz
          if-no-files-found: error
  deploy-neocities:
    needs: build-static
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
      - name: Rename 404 page to Neocities convention
        run: mv static/404.html static/not_found.html
      - uses: bcomnes/deploy-to-neocities@v2
        with:
          api_token: ${{ secrets.NEOCITIES_API_TOKEN }}
          cleanup: true
          dist_dir: static

  deploy-vps:
    needs: build-server
    runs-on: ubuntu-latest
    steps:
      - name: Download image artifact
        uses: actions/download-artifact@v4
        with:
          name: website-image

      - name: Initialize ssh
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.HOST_NAME }} > ~/.ssh/known_hosts

      - name: Ship image and restart
        run: |
          rsync -av --chmod=600 website-image.tar.gz ${{ secrets.USERNAME }}@${{ secrets.HOST_NAME }}:~/website/
          ssh ${{ secrets.USERNAME }}@${{ secrets.HOST_NAME }} \
            "docker load -i ~/website/website-image.tar.gz > /dev/null && rm ~/website/website-image.tar.gz && ~/entrypoint.sh"
