name: "Deploy website to hosts"

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    uses: a1ts-a1t/alts-alt.website/.github/workflows/build.yml@main

  deploy-neocities:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4

      - name: Deploy to Neocities
        uses: bcomnes/deploy-to-neocities@v2
        with:
          api_token: ${{ secrets.NEOCITIES_API_TOKEN }}
          cleanup: true
          dist_dir: build

  deploy-alts-alt:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4

      - name: Initialize ssh
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.HOST_NAME }} > ~/.ssh/known_hosts

      - name: Sync build directory
        run: rsync -av --delete build ${{ secrets.USERNAME }}@${{ secrets.HOST_NAME }}:~/alts-alt

      - name: Restart server
        run: ssh ${{ secrets.HOST_USERNAME }}@${{ secrets.HOST_NAME }} "~/alts-alt/entrypoint.sh"

