name: "Deploy website to hosts"

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  NODE_ENV: "production"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build deployment artifacts
        run: npm run build

      - name: Copy index to 404 backup
        run: cp index.html not_found.html
        working-directory: "./dist/"

      - name: Publish build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: dist/
          if-no-files-found: error
          overwrite: true

  deploy-neocities:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4

      - name: Deploy to Neocities
        uses: bcomnes/deploy-to-neocities@v2
        with:
          api_token: ${{ secrets.NEOCITIES_API_TOKEN }}
          cleanup: true
          dist_dir: build

  deploy-alts-alt:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4

      - name: Initialize ssh
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.HOST_NAME }} > ~/.ssh/known_hosts

      - name: Sync build directory
        run: rsync -av --delete build ${{ secrets.USERNAME }}@${{ secrets.HOST_NAME }}:~/alts-alt

      - name: Restart server
        run: ssh ${{ secrets.USERNAME }}@${{ secrets.HOST_NAME }} "~/alts-alt/entrypoint.sh"

